name: Sync to Upyun

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download and install upx
      run: |
        UPX_VERSION="v0.4.6"
        wget https://github.com/upyun/upx/releases/download/${UPX_VERSION}/upx_0.4.6_linux_amd64.tar.gz -O upx.tar.gz
        tar -xzf upx.tar.gz
        chmod +x upx
        sudo mv upx /usr/local/bin/

    - name: Create upx config file
      run: |
        mkdir -p /home/runner/.config/upx
        echo "[default]" > /home/runner/.config/upx/config
        echo "username = ${UPYUN_OPERATOR}" >> /home/runner/.config/upx/config
        echo "password = ${UPYUN_PASSWORD}" >> /home/runner/.config/upx/config
        echo "bucket = ${UPYUN_SERVICE}" >> /home/runner/.config/upx/config
        
    - name: Sync directories to Upyun
      env:
        UPYUN_SERVICE: ${{ secrets.UPYUN_SERVICE }}
        UPYUN_OPERATOR: ${{ secrets.UPYUN_OPERATOR }}
        UPYUN_PASSWORD: ${{ secrets.UPYUN_PASSWORD }}
      run: |
        # 同步第一个目录
        upx sync /snake /github/snake
        # 同步第二个目录
        # upx sync /path/to/local/directory2 /path/to/remote/directory2
