name: Sync to Upyun

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download upx
      run: |
        UPX_VERSION=$(curl -s https://api.github.com/repos/upyun/upx/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
        wget https://github.com/upyun/upx/releases/download/${UPX_VERSION}/upx-linux-amd64 -O upx
        chmod +x upx
        sudo mv upx /usr/local/bin/
    - name: Sync directories to Upyun
      env:
        UPYUN_SERVICE: ${{ secrets.UPYUN_SERVICE }}
        UPYUN_OPERATOR: ${{ secrets.UPYUN_OPERATOR }}
        UPYUN_PASSWORD: ${{ secrets.UPYUN_PASSWORD }}
      run: |
        # 同步第一个目录
        upx sync /snake /github/snake
        # 同步第二个目录
        # upx sync /path/to/local/directory2 /path/to/remote/directory2
